#include "backend/runtime_c.h"

void re0_runtime_conversion_emit(Re0Buffer *out) {
    re0_buffer_write_str(out,
        "#ifndef __REO_CONV_ALLOC\n"
        "#define __REO_CONV_ALLOC __reo_gc_try_alloc\n"
        "#endif\n"
        "#include <errno.h>\n"
        "#include <float.h>\n"
        "#include <limits.h>\n"
        "#include <math.h>\n"
        "\n"
        "#if !defined(__SIZEOF_INT128__)\n"
        "#error \"RingEcho conversion runtime requires a target with 128-bit integer support\"\n"
        "#endif\n"
        "__extension__ typedef unsigned __int128 __reo_u128;\n"
        "__extension__ typedef __int128 __reo_i128;\n"
        "enum { __REO_CONV_FORMAT = 1, __REO_CONV_RANGE, __REO_CONV_NONFINITE,\n"
        "       __REO_CONV_LENGTH, __REO_CONV_MEMORY, __REO_CONV_MAX_TEXT = 4096 };\n"
        "\n"
        "static void __reo_conversion_error(int error) {\n"
        "    fprintf(stderr, \"runtime error: conversion failed (%d)\\n\", error);\n"
        "    abort();\n"
        "}\n"
        "static __reo_u128 __reo_conv_mask(unsigned bits) {\n"
        "    return bits == 128 ? ~(__reo_u128)0 : (((__reo_u128)1 << bits) - 1);\n"
        "}\n"
        "static __reo_i128 __reo_conv_signed(__reo_u128 value, unsigned bits) {\n"
        "    __reo_u128 mask = __reo_conv_mask(bits);\n"
        "    value &= mask;\n"
        "    if (value & ((__reo_u128)1 << (bits - 1)))\n"
        "        return -1 - (__reo_i128)(mask - value);\n"
        "    return (__reo_i128)value;\n"
        "}\n"
        "static __reo_u128 __reo_conv_float_unsigned(double value, unsigned bits) {\n"
        "    __reo_u128 max = __reo_conv_mask(bits);\n");
    re0_buffer_write_str(out,
        "    double upper = bits == 128 ? (double)((__reo_u128)1 << 127) * 2.0\n"
        "                               : (double)((__reo_u128)1 << bits);\n"
        "    if (isnan(value) || value <= 0.0) return 0;\n"
        "    if (value >= upper) return max;\n"
        "    return (__reo_u128)value;\n"
        "}\n"
        "static __reo_i128 __reo_conv_float_signed(double value, unsigned bits) {\n"
        "    __reo_u128 sign = (__reo_u128)1 << (bits - 1);\n"
        "    double upper = (double)sign;\n"
        "    if (isnan(value)) return 0;\n"
        "    if (value >= upper) return (__reo_i128)(sign - 1);\n"
        "    if (value <= -upper) return -1 - (__reo_i128)(sign - 1);\n"
        "    return (__reo_i128)value;\n"
        "}\n"
        "static float __reo_conv_f32(double value) {\n"
        "    if (value > FLT_MAX) return INFINITY;\n"
        "    if (value < -FLT_MAX) return -INFINITY;\n"
        "    return (float)value;\n"
        "}\n"
        "static int __reo_conv_parse_integer(const char *text, unsigned bits, bool signed_target,\n"
        "                                    __reo_u128 *value) {\n"
        "    if (!text || !value || !text[0]) return __REO_CONV_FORMAT;\n"
        "    bool negative = text[0] == '-';\n"
        "    size_t i = (negative || text[0] == '+') ? 1 : 0;\n"
        "    if (!text[i]) return __REO_CONV_FORMAT;\n"
        "    __reo_u128 limit = signed_target ? ((__reo_u128)1 << (bits - 1))\n"
        "                                      : __reo_conv_mask(bits);\n"
        "    if (signed_target && !negative) limit--;\n"
        "    if (negative && !signed_target) return __REO_CONV_RANGE;\n"
        "    __reo_u128 result = 0;\n"
        "    for (; i < __REO_CONV_MAX_TEXT && text[i]; i++) {\n"
        "        if (text[i] < '0' || text[i] > '9') return __REO_CONV_FORMAT;\n");
    re0_buffer_write_str(out,
        "        unsigned digit = (unsigned)(text[i] - '0');\n"
        "        if (result > limit / 10 || (result == limit / 10 && digit > limit % 10))\n"
        "            return __REO_CONV_RANGE;\n"
        "        result = result * 10 + digit;\n"
        "    }\n"
        "    if (i == __REO_CONV_MAX_TEXT) return __REO_CONV_LENGTH;\n"
        "    *value = negative ? (__reo_u128)0 - result : result;\n"
        "    return 0;\n"
        "}\n"
        "static __reo_u128 __reo_conv_string_integer(const char *text, unsigned bits, bool signed_target) {\n"
        "    __reo_u128 value = 0;\n"
        "    int error = __reo_conv_parse_integer(text, bits, signed_target, &value);\n"
        "    if (error) __reo_conversion_error(error);\n"
        "    return value;\n"
        "}\n"
        "static int __reo_conv_parse_float(const char *text, double *value) {\n"
        "    if (!text || !value || !text[0]) return __REO_CONV_FORMAT;\n"
        "    size_t size = 0;\n"
        "    while (size < __REO_CONV_MAX_TEXT && text[size]) size++;\n"
        "    if (size == __REO_CONV_MAX_TEXT) return __REO_CONV_LENGTH;\n"
        "    if (text[0] == ' ' || text[0] == '\\t' || text[0] == '\\n' || text[0] == '\\r' ||\n"
        "        text[0] == '\\v' || text[0] == '\\f') return __REO_CONV_FORMAT;\n"
        "    char *end = NULL;\n"
        "    errno = 0;\n"
        "    double result = strtod(text, &end);\n"
        "    if (end == text || !end || *end) return __REO_CONV_FORMAT;\n"
        "    if (errno == ERANGE) return __REO_CONV_RANGE;\n"
        "    *value = result;\n"
        "    return 0;\n"
        "}\n"
        "static double __reo_conv_string_float(const char *text) {\n"
        "    double value = 0;\n");
    re0_buffer_write_str(out,
        "    int error = __reo_conv_parse_float(text, &value);\n"
        "    if (error) __reo_conversion_error(error);\n"
        "    return value;\n"
        "}\n"
        "static bool __reo_conv_string_bool(const char *text) {\n"
        "    if (text && strcmp(text, \"true\") == 0) return true;\n"
        "    if (text && strcmp(text, \"false\") == 0) return false;\n"
        "    __reo_conversion_error(__REO_CONV_FORMAT);\n"
        "    return false;\n"
        "}\n"
        "static uint8_t __reo_conv_string_char(const char *text) {\n"
        "    if (!text || !text[0] || text[1]) __reo_conversion_error(__REO_CONV_LENGTH);\n"
        "    return (uint8_t)text[0];\n"
        "}\n"
        "static const char *__reo_conv_require_string(const char *value) {\n"
        "    if (!value) __reo_conversion_error(__REO_CONV_MEMORY);\n"
        "    return value;\n"
        "}\n"
        "static const char *__reo_conv_unsigned_string(__reo_u128 value) {\n"
        "    char digits[40];\n"
        "    size_t used = 0;\n"
        "    do { digits[used++] = (char)('0' + value % 10); value /= 10; } while (value);\n"
        "    char *result = __REO_CONV_ALLOC(used + 1);\n"
        "    if (!result) return NULL;\n"
        "    for (size_t i = 0; i < used; i++) result[i] = digits[used - i - 1];\n"
        "    result[used] = 0;\n"
        "    return result;\n"
        "}\n"
        "static const char *__reo_conv_signed_string(__reo_i128 value) {\n"
        "    if (value >= 0) return __reo_conv_unsigned_string((__reo_u128)value);\n"
        "    __reo_u128 magnitude = (__reo_u128)0 - (__reo_u128)value;\n"
        "    char digits[40];\n");
    re0_buffer_write_str(out,
        "    size_t used = 0;\n"
        "    do { digits[used++] = (char)('0' + magnitude % 10); magnitude /= 10; } while (magnitude);\n"
        "    char *result = __REO_CONV_ALLOC(used + 2);\n"
        "    if (!result) return NULL;\n"
        "    result[0] = '-';\n"
        "    for (size_t i = 0; i < used; i++) result[i + 1] = digits[used - i - 1];\n"
        "    result[used + 1] = 0;\n"
        "    return result;\n"
        "}\n"
        "static const char *__reo_conv_float_string(double value) {\n"
        "    char *result = __REO_CONV_ALLOC(32);\n"
        "    if (!result) return NULL;\n"
        "    snprintf(result, 32, \"%.17g\", value);\n"
        "    return result;\n"
        "}\n"
        "static const char *__reo_conv_char_string(uint8_t value) {\n"
        "    if (!value) __reo_conversion_error(__REO_CONV_FORMAT);\n"
        "    char *result = __REO_CONV_ALLOC(2);\n"
        "    if (!result) return NULL;\n"
        "    result[0] = (char)value;\n"
        "    result[1] = 0;\n"
        "    return result;\n"
        "}\n"
        "static __reo_u128 __reo_conv_binary(__reo_u128 a, __reo_u128 b, unsigned bits,\n"
        "                                    bool signed_type, unsigned operation) {\n"
        "    __reo_u128 mask = __reo_conv_mask(bits);\n"
        "    a &= mask;\n"
        "    b &= mask;\n"
        "    if (operation == 0) return (a + b) & mask;\n"
        "    if (operation == 1) return (a - b) & mask;\n"
        "    if (operation == 2) return (a * b) & mask;\n"
        "    if (operation == 5) return (a << ((unsigned)b & (bits - 1))) & mask;\n");
    re0_buffer_write_str(out,
        "    if (operation == 6) {\n"
        "        unsigned shift = (unsigned)b & (bits - 1);\n"
        "        __reo_u128 result = a >> shift;\n"
        "        if (signed_type && shift && (a & ((__reo_u128)1 << (bits - 1))))\n"
        "            result |= mask ^ (mask >> shift);\n"
        "        return result;\n"
        "    }\n"
        "    if (!b) { fputs(\"runtime error: division by zero\\n\", stderr); abort(); }\n"
        "    if (!signed_type) return operation == 3 ? a / b : a % b;\n"
        "    __reo_i128 left = __reo_conv_signed(a, bits), right = __reo_conv_signed(b, bits);\n"
        "    if (a == ((__reo_u128)1 << (bits - 1)) && right == -1) {\n"
        "        fputs(\"runtime error: division overflow\\n\", stderr); abort();\n"
        "    }\n"
        "    return (__reo_u128)(operation == 3 ? left / right : left % right);\n"
        "}\n"
        "enum { __REO_VALUE_SIGNED, __REO_VALUE_UNSIGNED, __REO_VALUE_FLOAT,\n"
        "       __REO_VALUE_BOOL, __REO_VALUE_CHAR, __REO_VALUE_STRING };\n"
        "typedef struct {\n"
        "    unsigned kind;\n"
        "    union { __reo_i128 signed_; __reo_u128 unsigned_; double floating; const char *string; } data;\n"
        "    int error;\n"
        "} __reo_value;\n"
        "static __reo_value __reo_box_signed(__reo_i128 x) { return (__reo_value){.kind=__REO_VALUE_SIGNED,.data.signed_=x}; }\n"
        "static __reo_value __reo_box_unsigned(__reo_u128 x) { return (__reo_value){.kind=__REO_VALUE_UNSIGNED,.data.unsigned_=x}; }\n"
        "static __reo_value __reo_box_float(double x) { return (__reo_value){.kind=__REO_VALUE_FLOAT,.data.floating=x}; }\n"
        "static __reo_value __reo_box_bool(bool x) { return (__reo_value){.kind=__REO_VALUE_BOOL,.data.unsigned_=x}; }\n"
        "static __reo_value __reo_box_char(uint8_t x) { return (__reo_value){.kind=__REO_VALUE_CHAR,.data.unsigned_=x}; }\n"
        "static __reo_value __reo_box_string(const char *x) { return (__reo_value){.kind=__REO_VALUE_STRING,.data.string=x}; }\n"
        "static bool __reo_integer_exact_float(__reo_u128 magnitude, unsigned precision) {\n"
        "    if (!magnitude) return true;\n"
        "    while (!(magnitude & 1)) magnitude >>= 1;\n"
        "    unsigned bits = 0;\n");
    re0_buffer_write_str(out,
        "    while (magnitude) { bits++; magnitude >>= 1; }\n"
        "    return bits <= precision;\n"
        "}\n"
        "static __reo_value __reo_checked_value(__reo_value source, unsigned target, unsigned bits) {\n"
        "    __reo_value result = {.kind=target};\n"
        "    if (source.kind == __REO_VALUE_STRING) {\n"
        "        const char *text = source.data.string;\n"
        "        if (target == __REO_VALUE_STRING) { result.data.string = text; return result; }\n"
        "        if (target == __REO_VALUE_FLOAT) {\n"
        "            result.error = __reo_conv_parse_float(text, &result.data.floating);\n"
        "            if (!result.error && bits == 32) {\n"
        "                double value = result.data.floating;\n"
        "                float narrowed = __reo_conv_f32(value);\n"
        "                if (isfinite(value) && !isfinite(narrowed)) result.error = __REO_CONV_RANGE;\n"
        "                result.data.floating = narrowed;\n"
        "            }\n"
        "            return result;\n"
        "        }\n"
        "        if (target == __REO_VALUE_BOOL) {\n"
        "            if (text && strcmp(text, \"true\") == 0) result.data.unsigned_ = 1;\n"
        "            else if (!text || strcmp(text, \"false\") != 0) result.error = __REO_CONV_FORMAT;\n"
        "            return result;\n"
        "        }\n"
        "        if (target == __REO_VALUE_CHAR) {\n"
        "            if (!text || !text[0] || text[1]) result.error = __REO_CONV_LENGTH;\n"
        "            else result.data.unsigned_ = (uint8_t)text[0];\n"
        "            return result;\n"
        "        }\n"
        "        __reo_u128 parsed = 0;\n"
        "        result.error = __reo_conv_parse_integer(text, bits, target == __REO_VALUE_SIGNED, &parsed);\n"
        "        if (target == __REO_VALUE_SIGNED) result.data.signed_ = __reo_conv_signed(parsed, bits);\n"
        "        else result.data.unsigned_ = parsed;\n");
    re0_buffer_write_str(out,
        "        return result;\n"
        "    }\n"
        "    if (target == __REO_VALUE_STRING) {\n"
        "        if (source.kind == __REO_VALUE_SIGNED) result.data.string = __reo_conv_signed_string(source.data.signed_);\n"
        "        else if (source.kind == __REO_VALUE_FLOAT) result.data.string = __reo_conv_float_string(source.data.floating);\n"
        "        else if (source.kind == __REO_VALUE_BOOL) result.data.string = source.data.unsigned_ ? \"true\" : \"false\";\n"
        "        else if (source.kind == __REO_VALUE_CHAR) {\n"
        "            if (!source.data.unsigned_) result.error = __REO_CONV_FORMAT;\n"
        "            else result.data.string = __reo_conv_char_string((uint8_t)source.data.unsigned_);\n"
        "        } else result.data.string = __reo_conv_unsigned_string(source.data.unsigned_);\n"
        "        if (!result.error && !result.data.string) result.error = __REO_CONV_MEMORY;\n"
        "        return result;\n"
        "    }\n"
        "    bool is_float = source.kind == __REO_VALUE_FLOAT;\n"
        "    bool negative = source.kind == __REO_VALUE_SIGNED && source.data.signed_ < 0;\n"
        "    __reo_u128 magnitude = is_float ? 0 : source.kind == __REO_VALUE_SIGNED\n"
        "        ? (negative ? (__reo_u128)0 - (__reo_u128)source.data.signed_ : (__reo_u128)source.data.signed_)\n"
        "        : source.data.unsigned_;\n"
        "    if (target == __REO_VALUE_BOOL) {\n"
        "        result.data.unsigned_ = is_float ? source.data.floating != 0.0 : magnitude != 0;\n"
        "        return result;\n"
        "    }\n"
        "    if (target == __REO_VALUE_FLOAT) {\n"
        "        double value = is_float ? source.data.floating : source.kind == __REO_VALUE_SIGNED\n"
        "                           ? (double)source.data.signed_ : (double)source.data.unsigned_;\n"
        "        if (!is_float && !__reo_integer_exact_float(magnitude, bits == 32 ? 24 : 53))\n"
        "            result.error = __REO_CONV_RANGE;\n"
        "        if (bits == 32) {\n"
        "            float narrow = __reo_conv_f32(value);\n"
        "            if (!isnan(value) && (double)narrow != value) result.error = __REO_CONV_RANGE;\n"
        "            value = narrow;\n"
        "        }\n");
    re0_buffer_write_str(out,
        "        result.data.floating = value;\n"
        "        return result;\n"
        "    }\n"
        "    bool signed_target = target == __REO_VALUE_SIGNED;\n"
        "    __reo_u128 limit = signed_target ? ((__reo_u128)1 << (bits - 1)) : __reo_conv_mask(bits);\n"
        "    if (is_float) {\n"
        "        double value = source.data.floating;\n"
        "        double upper = signed_target ? (double)limit : bits == 128\n"
        "            ? (double)((__reo_u128)1 << 127) * 2.0 : (double)((__reo_u128)1 << bits);\n"
        "        if (!isfinite(value)) result.error = __REO_CONV_NONFINITE;\n"
        "        else if (value >= upper || value < (signed_target ? -upper : 0.0)) result.error = __REO_CONV_RANGE;\n"
        "        if (!result.error) {\n"
        "            if (signed_target) result.data.signed_ = (__reo_i128)value;\n"
        "            else result.data.unsigned_ = (__reo_u128)value;\n"
        "        }\n"
        "        return result;\n"
        "    }\n"
        "    if (signed_target && !negative) limit--;\n"
        "    if ((negative && !signed_target) || magnitude > limit) result.error = __REO_CONV_RANGE;\n"
        "    if (!result.error) {\n"
        "        if (signed_target) result.data.signed_ = negative ? -1 - (__reo_i128)(magnitude - 1) : (__reo_i128)magnitude;\n"
        "        else result.data.unsigned_ = magnitude;\n"
        "    }\n"
        "    return result;\n"
        "}\n"
        "#define __REO_DEFINE_TRY(NAME, TYPE, KIND, BITS, FIELD) \\\n"
        "    typedef struct { int64_t tag; TYPE value; int64_t error; int64_t index; } __reo_result_##NAME; \\\n"
        "    static __reo_result_##NAME __reo_try_##NAME(__reo_value source) { \\\n"
        "        __reo_value converted = __reo_checked_value(source, KIND, BITS); \\\n"
        "        __reo_result_##NAME result = {0}; \\\n"
        "        result.tag = converted.error ? 1 : 0; \\\n"
        "        result.error = converted.error; result.index = -1; \\\n");
    re0_buffer_write_str(out,
        "        if (!converted.error) result.value = (TYPE)converted.data.FIELD; \\\n"
        "        return result; \\\n"
        "    }\n"
        "__REO_DEFINE_TRY(i8, int8_t, __REO_VALUE_SIGNED, 8, signed_)\n"
        "__REO_DEFINE_TRY(i16, int16_t, __REO_VALUE_SIGNED, 16, signed_)\n"
        "__REO_DEFINE_TRY(i32, int32_t, __REO_VALUE_SIGNED, 32, signed_)\n"
        "__REO_DEFINE_TRY(i64, int64_t, __REO_VALUE_SIGNED, 64, signed_)\n"
        "__REO_DEFINE_TRY(i128, __reo_i128, __REO_VALUE_SIGNED, 128, signed_)\n"
        "__REO_DEFINE_TRY(isize, intptr_t, __REO_VALUE_SIGNED, sizeof(intptr_t)*CHAR_BIT, signed_)\n"
        "__REO_DEFINE_TRY(u8, uint8_t, __REO_VALUE_UNSIGNED, 8, unsigned_)\n"
        "__REO_DEFINE_TRY(u16, uint16_t, __REO_VALUE_UNSIGNED, 16, unsigned_)\n"
        "__REO_DEFINE_TRY(u32, uint32_t, __REO_VALUE_UNSIGNED, 32, unsigned_)\n"
        "__REO_DEFINE_TRY(u64, uint64_t, __REO_VALUE_UNSIGNED, 64, unsigned_)\n"
        "__REO_DEFINE_TRY(u128, __reo_u128, __REO_VALUE_UNSIGNED, 128, unsigned_)\n"
        "__REO_DEFINE_TRY(usize, uintptr_t, __REO_VALUE_UNSIGNED, sizeof(uintptr_t)*CHAR_BIT, unsigned_)\n"
        "__REO_DEFINE_TRY(f32, float, __REO_VALUE_FLOAT, 32, floating)\n"
        "__REO_DEFINE_TRY(f64, double, __REO_VALUE_FLOAT, 64, floating)\n"
        "__REO_DEFINE_TRY(bool, bool, __REO_VALUE_BOOL, 1, unsigned_)\n"
        "__REO_DEFINE_TRY(char, uint8_t, __REO_VALUE_CHAR, 8, unsigned_)\n"
        "__REO_DEFINE_TRY(str, const char*, __REO_VALUE_STRING, 0, string)\n"
        "#undef __REO_DEFINE_TRY\n"
        "\n"
        "typedef struct { __reo_u128 *data; int64_t len; } __reo_arr128_t;\n"
        "#define __REO_MAX_ARRAY_ELEMENTS 1048576\n"
        "static __reo_arr128_t __reo_arr128_rep(int64_t count, __reo_u128 value) {\n"
        "    if (count < 0 || count > __REO_MAX_ARRAY_ELEMENTS || (uint64_t)count > SIZE_MAX / sizeof(__reo_u128))\n"
        "        __reo_conversion_error(__REO_CONV_LENGTH);\n"
        "    __reo_arr128_t result = {0};\n"
        "    if (!count) return result;\n"
        "    result.data = __REO_CONV_ALLOC((size_t)count * sizeof(*result.data));\n"
        "    if (!result.data) __reo_conversion_error(__REO_CONV_MEMORY);\n"
        "    result.len = count;\n");
    re0_buffer_write_str(out,
        "    for (int64_t i = 0; i < count; i++) result.data[i] = value;\n"
        "    return result;\n"
        "}\n"
        "static __reo_arr128_t __reo_arr128_lit(const __reo_u128 *source, int64_t count) {\n"
        "    if (!source && count) __reo_conversion_error(__REO_CONV_FORMAT);\n"
        "    __reo_arr128_t result = __reo_arr128_rep(count, 0);\n"
        "    if (count) memcpy(result.data, source, (size_t)count * sizeof(*source));\n"
        "    return result;\n"
        "}\n"
        "static __reo_u128 __reo_arr128_get(__reo_arr128_t *array, int64_t index) {\n"
        "    if (!array || index < 0 || index >= array->len) __reo_conversion_error(__REO_CONV_RANGE);\n"
        "    return array->data[index];\n"
        "}\n"
        "static void __reo_arr128_set(__reo_arr128_t *array, int64_t index, __reo_u128 value) {\n"
        "    if (!array || index < 0 || index >= array->len) __reo_conversion_error(__REO_CONV_RANGE);\n"
        "    array->data[index] = value;\n"
        "}\n"
        "#ifndef __REO_CONV_FREE\n"
        "#define __REO_CONV_FREE __reo_gc_free\n"
        "#endif\n"
        "#ifdef __REO_FREESTANDING\n"
        "typedef struct { int64_t *data; int64_t len; } __reo_arr_t;\n"
        "typedef struct { double *data; int64_t len; } __reo_arrf_t;\n"
        "#endif\n"
        "static __reo_value __reo_array_source(const void *data, int64_t index, unsigned kind, unsigned bits) {\n"
        "    if (kind == __REO_VALUE_FLOAT) return __reo_box_float(((const double*)data)[index]);\n"
        "    __reo_u128 raw = bits == 128 ? ((const __reo_u128*)data)[index]\n"
        "                                 : (__reo_u128)(uint64_t)((const int64_t*)data)[index];\n"
        "    if (kind == __REO_VALUE_SIGNED) return __reo_box_signed(__reo_conv_signed(raw, bits));\n"
        "    if (kind == __REO_VALUE_BOOL) return __reo_box_bool(raw != 0);\n"
        "    if (kind == __REO_VALUE_CHAR) return __reo_box_char((uint8_t)raw);\n"
        "    return __reo_box_unsigned(raw & __reo_conv_mask(bits));\n");
    re0_buffer_write_str(out,
        "}\n"
        "#define __REO_DEFINE_ARRAY_TRY(NAME, ARRAY, SLOT, KIND, BITS, FIELD) \\\n"
        "    typedef struct { int64_t tag; ARRAY value; int64_t error; int64_t index; } __reo_result_array_##NAME; \\\n"
        "    static __reo_result_array_##NAME __reo_try_array_##NAME(const void *data, int64_t count, \\\n"
        "            unsigned source_kind, unsigned source_bits, int64_t expected) { \\\n"
        "        __reo_result_array_##NAME result = {0}; \\\n"
        "        result.index = -1; \\\n"
        "        if (count < 0 || count > __REO_MAX_ARRAY_ELEMENTS || (!data && count) || \\\n"
        "            (expected >= 0 && expected != count) || (uint64_t)count > SIZE_MAX / sizeof(SLOT)) { \\\n"
        "            result.tag = 1; result.error = __REO_CONV_LENGTH; return result; \\\n"
        "        } \\\n"
        "        SLOT *values = count ? __REO_CONV_ALLOC((size_t)count * sizeof(SLOT)) : NULL; \\\n"
        "        if (!values && count) { result.tag=1; result.error=__REO_CONV_MEMORY; return result; } \\\n"
        "        for (int64_t i = 0; i < count; i++) { \\\n"
        "            __reo_value value = __reo_checked_value(__reo_array_source(data, i, source_kind, source_bits), KIND, BITS); \\\n"
        "            if (value.error) { \\\n"
        "                __REO_CONV_FREE(values); result.tag=1; result.error=value.error; result.index=i; return result; \\\n"
        "            } \\\n"
        "            if (KIND == __REO_VALUE_FLOAT) values[i] = (SLOT)value.data.floating; \\\n"
        "            else if (sizeof(SLOT) == sizeof(int64_t)) values[i] = (SLOT)__reo_conv_signed((__reo_u128)value.data.FIELD, 64); \\\n"
        "            else values[i] = (SLOT)value.data.FIELD; \\\n"
        "        } \\\n"
        "        result.value.data=values; result.value.len=count; return result; \\\n"
        "    }\n"
        "__REO_DEFINE_ARRAY_TRY(i8, __reo_arr_t, int64_t, __REO_VALUE_SIGNED, 8, signed_)\n"
        "__REO_DEFINE_ARRAY_TRY(i16, __reo_arr_t, int64_t, __REO_VALUE_SIGNED, 16, signed_)\n"
        "__REO_DEFINE_ARRAY_TRY(i32, __reo_arr_t, int64_t, __REO_VALUE_SIGNED, 32, signed_)\n"
        "__REO_DEFINE_ARRAY_TRY(i64, __reo_arr_t, int64_t, __REO_VALUE_SIGNED, 64, signed_)\n"
        "__REO_DEFINE_ARRAY_TRY(i128, __reo_arr128_t, __reo_u128, __REO_VALUE_SIGNED, 128, signed_)\n"
        "__REO_DEFINE_ARRAY_TRY(isize, __reo_arr_t, int64_t, __REO_VALUE_SIGNED, sizeof(intptr_t)*CHAR_BIT, signed_)\n"
        "__REO_DEFINE_ARRAY_TRY(u8, __reo_arr_t, int64_t, __REO_VALUE_UNSIGNED, 8, unsigned_)\n"
        "__REO_DEFINE_ARRAY_TRY(u16, __reo_arr_t, int64_t, __REO_VALUE_UNSIGNED, 16, unsigned_)\n");
    re0_buffer_write_str(out,
        "__REO_DEFINE_ARRAY_TRY(u32, __reo_arr_t, int64_t, __REO_VALUE_UNSIGNED, 32, unsigned_)\n"
        "__REO_DEFINE_ARRAY_TRY(u64, __reo_arr_t, int64_t, __REO_VALUE_UNSIGNED, 64, unsigned_)\n"
        "__REO_DEFINE_ARRAY_TRY(u128, __reo_arr128_t, __reo_u128, __REO_VALUE_UNSIGNED, 128, unsigned_)\n"
        "__REO_DEFINE_ARRAY_TRY(usize, __reo_arr_t, int64_t, __REO_VALUE_UNSIGNED, sizeof(uintptr_t)*CHAR_BIT, unsigned_)\n"
        "__REO_DEFINE_ARRAY_TRY(f32, __reo_arrf_t, double, __REO_VALUE_FLOAT, 32, floating)\n"
        "__REO_DEFINE_ARRAY_TRY(f64, __reo_arrf_t, double, __REO_VALUE_FLOAT, 64, floating)\n"
        "__REO_DEFINE_ARRAY_TRY(bool, __reo_arr_t, int64_t, __REO_VALUE_BOOL, 1, unsigned_)\n"
        "__REO_DEFINE_ARRAY_TRY(char, __reo_arr_t, int64_t, __REO_VALUE_CHAR, 8, unsigned_)\n"
        "#undef __REO_DEFINE_ARRAY_TRY\n");
}
