#include "backend/runtime_c.h"

/* Embedded C runtime library:
 * Emitted verbatim as the prelude of every generated program.
 * Extracted from backend_c.c so the file layout matches responsibilities:
 * backend_c.c = code generation, runtime_c.c = the target runtime. */

void re0_runtime_c_emit(Re0Buffer *out) {
    re0_buffer_write_str(out,
        "#include <stdint.h>\n#include <stdbool.h>\n"
        "#include <stdio.h>\n#include <stdlib.h>\n#include <string.h>\n"
        "#include <dirent.h>\n#include <sys/stat.h>\n\n"
        /* Option/Result core enum types */
        "typedef struct { int64_t tag; union { int64_t v0; } u; } Option;\n"
        "typedef struct { int64_t tag; union { int64_t v0; } u; } Result;\n"
        "typedef int64_t __reo_fn_ptr;\n\n"
        /* runtime safety helpers */
        "static int64_t __reo_safe_div(int64_t a, int64_t b) {\n"
        "    if (b == 0) { fprintf(stderr, \"runtime error: division by zero\\n\"); abort(); }\n"
        "    if (a == INT64_MIN && b == -1) { fprintf(stderr, \"runtime error: division overflow\\n\"); abort(); }\n"
        "    return a / b;\n"
        "}\n"
        "static int64_t __reo_safe_mod(int64_t a, int64_t b) {\n"
        "    if (b == 0) { fprintf(stderr, \"runtime error: division by zero\\n\"); abort(); }\n"
        "    if (a == INT64_MIN && b == -1) { fprintf(stderr, \"runtime error: division overflow\\n\"); abort(); }\n"
        "    return a % b;\n"
        "}\n"
        "static int64_t __reo_safe_shl(int64_t a, int64_t b) {\n"
        "    return a << (b & 63);\n"
        "}\n"
        "static int64_t __reo_safe_shr(int64_t a, int64_t b) {\n"
        "    return a >> (b & 63);\n"
        "}\n"
        /* __reo_safe_narrow: well-defined wrapping (Rust `as` semantics), no abort.
           The outer C cast interprets the returned value in the destination type. */
        "static int64_t __reo_safe_narrow(int64_t v, size_t bytes, const char* ty) {\n"
        "    if (bytes == 0 || bytes >= 8) return v;\n"
        "    unsigned bits = (unsigned)(bytes * 8);\n"
        "    uint64_t mask = (((uint64_t)1) << bits) - 1;\n"
        "    uint64_t u = (uint64_t)v & mask;\n"
        "    if (ty && ty[0] == 'u') return (int64_t)u;\n"
        "    uint64_t sign = ((uint64_t)1) << (bits - 1);\n"
        "    if (u & sign) u |= ~mask;\n"
        "    return (int64_t)u;\n"
        "}\n"
        "static int64_t __reo_safe_f2i(double v, const char* ty) {\n"
        "    if (v != v) return 0;\n"
        "    if (ty && (strncmp(ty, \"uint\", 4) == 0 || strncmp(ty, \"int\", 3) == 0)) {\n"
        "        /* narrow integer target (intN_t / uintN_t, N < 64):\n"
        "         * saturate to the target range like Rust `as` (no wrap).\n"
        "         * digits start at index 4 for uintN_t, 3 for intN_t. */\n"
        "        const char* d = ty + (ty[0] == 'u' ? 4 : 3);\n"
        "        int bits;\n"
        "        if (d[0] == '8') bits = 8;\n"
        "        else if (d[0] == '1' && d[1] == '6') bits = 16;\n"
        "        else if (d[0] == '3' && d[1] == '2') bits = 32;\n"
        "        else bits = 64;\n"
        "        if (bits < 64) {\n"
        "            if (ty[0] == 'u') {\n"
        "                double max = (double)(((((uint64_t)1) << (bits - 1)) - 1) * 2 + 1);\n"
        "                if (v == (double)(1.0/0.0)) return (int64_t)(uint64_t)max;\n"
        "                if (v == (double)(-1.0/0.0) || v < 0.0) return 0;\n"
        "                if (v > max) return (int64_t)(uint64_t)max;\n"
        "                return (int64_t)(uint64_t)v;\n"
        "            } else {\n"
        "                double max = (double)(((int64_t)1) << (bits - 1)) - 1.0;\n"
        "                double min = -max - 1.0;\n"
        "                if (v == (double)(1.0/0.0)) return (int64_t)max;\n"
        "                if (v == (double)(-1.0/0.0)) return (int64_t)min;\n"
        "                if (v > max) return (int64_t)max;\n"
        "                if (v < min) return (int64_t)min;\n"
        "                return (int64_t)v;\n"
        "            }\n"
        "        }\n"
        "    }\n"
        "    if (ty && strcmp(ty, \"bool\") == 0) return v != 0.0;\n"
        "    if (v == (double)(1.0/0.0)) return 9223372036854775807LL;\n"
        "    if (v == (double)(-1.0/0.0)) return (-9223372036854775807LL - 1);\n"
        "    if (v > (double)9223372036854775807LL) return 9223372036854775807LL;\n"
        "    if (v < (double)(-9223372036854775807LL - 1)) return (-9223372036854775807LL - 1);\n"
        "    return (int64_t)v;\n"
        "}\n"
        "static void __reo_print_u128(unsigned __int128 v) {\n"
        "    char buf[41]; char *p = buf + sizeof(buf) - 1; *p = '\\0';\n"
        "    if (v == 0) { *(--p) = '0'; }\n"
        "    else { while (v > 0) { *(--p) = (char)('0' + (int)(v % 10)); v /= 10; } }\n"
        "    printf(\"%s\\n\", p);\n"
        "}\n"
        "static void __reo_print_i128(__int128 v) {\n"
        "    if (v < 0) { putchar('-'); __reo_print_u128((unsigned __int128)(-v)); }\n"
        "    else __reo_print_u128((unsigned __int128)v);\n"
        "}\n"
        /* string helpers */
        "static int64_t __reo_str_len(const char* s) { return s ? (int64_t)strlen(s) : 0; }\n"
        "static const char* __reo_str_concat(const char* a, const char* b) {\n"
        "    if (!a) a = \"\"; if (!b) b = \"\";\n"
        "    size_t la = strlen(a), lb = strlen(b);\n"
        "    char* r = (char*)malloc(la + lb + 1);\n"
        "    memcpy(r, a, la); memcpy(r + la, b, lb); r[la + lb] = 0;\n"
        "    return r;\n"
        "}\n"
        "static bool __reo_str_eq(const char* a, const char* b) {\n"
        "    if (!a) a = \"\"; if (!b) b = \"\";\n"
        "    return strcmp(a, b) == 0;\n"
        "}\n"
        "static int64_t __reo_str_to_int(const char* s) {\n"
        "    return s ? strtoll(s, NULL, 10) : 0;\n"
        "}\n"
        "static double __reo_str_to_f64(const char* s) {\n"
        "    return s ? strtod(s, NULL) : 0.0;\n"
        "}\n"
        "static const char* __reo_f64_to_str(double v) {\n"
        "    char* r = (char*)malloc(64);\n"
        "    snprintf(r, 64, \"%g\", v);\n"
        "    return r;\n"
        "}\n"
        "static const char* __reo_str_slice(const char* s, int64_t start, int64_t end) {\n"
        "    if (!s) return \"\";\n"
        "    int64_t len = (int64_t)strlen(s);\n"
        "    if (start < 0) start = 0;\n"
        "    if (end > len) end = len;\n"
        "    if (start >= end) return \"\";\n"
        "    char* r = (char*)malloc((size_t)(end - start) + 1);\n"
        "    memcpy(r, s + start, (size_t)(end - start)); r[end - start] = 0;\n"
        "    return r;\n"
        "}\n"
        "static char __reo_str_char_at(const char* s, int64_t i) {\n"
        "    if (!s || i < 0 || i >= (int64_t)strlen(s)) return 0;\n"
        "    return s[i];\n"
        "}\n"
        "static const char* __reo_char_to_str(char c) {\n"
        "    char* r = (char*)malloc(2); r[0] = c; r[1] = 0; return r;\n"
        "}\n"
        "static const char* __reo_to_string(int64_t v) {\n"
        "    char* r = (char*)malloc(32); snprintf(r, 32, \"%lld\", (long long)v); return r;\n"
        "}\n"
        "static bool __reo_is_digit(char c) { return c >= '0' && c <= '9'; }\n"
        "static bool __reo_is_alpha(char c) { return (c >= 'a' && c <= 'z') || (c >= 'A' && c <= 'Z') || c == '_'; }\n"
        "static bool __reo_is_alnum(char c) { return __reo_is_digit(c) || __reo_is_alpha(c); }\n");
    re0_buffer_write_str(out,
        /* file I/O with path traversal protection */
        "static const char* __reo_file_read(const char* path) {\n"
        "    if (!path || strstr(path, \"..\")) { fprintf(stderr, \"runtime error: invalid path\\n\"); abort(); }\n"
        "    FILE* f = fopen(path, \"rb\");\n"
        "    if (!f) return \"\";\n"
        "    fseek(f, 0, SEEK_END); long sz = ftell(f); fseek(f, 0, SEEK_SET);\n"
        "    if (sz < 0 || sz > 16777216) { fclose(f); return \"\"; }\n"
        "    char* r = (char*)malloc((size_t)sz + 1);\n"
        "    size_t rd = fread(r, 1, (size_t)sz, f); r[rd] = 0; fclose(f);\n"
        "    return r;\n"
        "}\n"
        "static void __reo_file_write(const char* path, const char* data) {\n"
        "    if (!path || strstr(path, \"..\")) { fprintf(stderr, \"runtime error: invalid path\\n\"); abort(); }\n"
        "    FILE* f = fopen(path, \"wb\");\n"
        "    if (!f) return;\n"
        "    if (data) fputs(data, f);\n"
        "    fclose(f);\n"
        "}\n"
        /* Vec helpers: Vec<T> is stored as { int64_t* ptr; int64_t len; int64_t cap } */
        "#define VEC_INIT_CAP 4\n"
        "typedef struct { int64_t* data; int64_t len; int64_t cap; } __reo_vec_t;\n"
        "static __reo_vec_t* __reo_vec_new(void) {\n"
        "    __reo_vec_t* v = (__reo_vec_t*)malloc(sizeof(__reo_vec_t));\n"
        "    if (!v) { fprintf(stderr, \"runtime error: out of memory\\n\"); abort(); }\n"
        "    v->data = (int64_t*)malloc(sizeof(int64_t) * VEC_INIT_CAP);\n"
        "    if (!v->data) { free(v); fprintf(stderr, \"runtime error: out of memory\\n\"); abort(); }\n"
        "    v->len = 0; v->cap = VEC_INIT_CAP; return v;\n"
        "}\n"
        "static void __reo_vec_push(__reo_vec_t* v, int64_t x) {\n"
        "    if (v->len >= v->cap) {\n"
        "        v->cap *= 2;\n"
        "        v->data = (int64_t*)realloc(v->data, sizeof(int64_t) * (size_t)v->cap);\n"
        "        if (!v->data) { fprintf(stderr, \"runtime error: out of memory\\n\"); abort(); }\n"
        "    }\n"
        "    v->data[v->len++] = x;\n"
        "}\n"
        "static int64_t __reo_vec_get(__reo_vec_t* v, int64_t i) {\n"
        "    if (i < 0 || i >= v->len) { fprintf(stderr, \"runtime error: index out of bounds\\n\"); abort(); }\n"
        "    return v->data[i];\n"
        "}\n"
        "static void __reo_vec_set(__reo_vec_t* v, int64_t i, int64_t x) {\n"
        "    if (i < 0 || i >= v->len) { fprintf(stderr, \"runtime error: index out of bounds\\n\"); abort(); }\n"
        "    v->data[i] = x;\n"
        "}\n"
        "static int64_t __reo_vec_pop(__reo_vec_t* v) {\n"
        "    if (v->len <= 0) { fprintf(stderr, \"runtime error: pop from empty vec\\n\"); abort(); }\n"
        "    return v->data[--v->len];\n"
        "}\n"
        "static int64_t __reo_vec_last(__reo_vec_t* v) {\n"
        "    if (v->len <= 0) { fprintf(stderr, \"runtime error: last on empty vec\\n\"); abort(); }\n"
        "    return v->data[v->len - 1];\n"
        "}\n"
        "static int64_t __reo_vec_len(__reo_vec_t* v) { return v->len; }\n"
        /* fixed-length array: heap-allocated so it can survive function return / be stored
            in a struct (stack compound literals would dangle). Uses malloc like vec
            (reclaimed at the language level by GC/program lifetime). */
        "static int64_t* __reo_array_repeat(int64_t n, int64_t val) {\n"
        "    if (n < 0) n = 0;\n"
        "    int64_t* a = (int64_t*)malloc(sizeof(int64_t) * (size_t)(n > 0 ? n : 1));\n"
        "    if (!a) { fprintf(stderr, \"runtime error: out of memory\\n\"); abort(); }\n"
        "    for (int64_t i = 0; i < n; i++) a[i] = val;\n"
        "    return a;\n"
        "}\n"
        "static int64_t* __reo_array_dup(const int64_t* src, int64_t n) {\n"
        "    if (n < 0) n = 0;\n"
        "    int64_t* a = (int64_t*)malloc(sizeof(int64_t) * (size_t)(n > 0 ? n : 1));\n"
        "    if (!a) { fprintf(stderr, \"runtime error: out of memory\\n\"); abort(); }\n"
        "    if (n > 0) memcpy(a, src, sizeof(int64_t) * (size_t)n);\n"
        "    return a;\n"
        "}\n"
        /* float arrays: same shape as int64 arrays but double-typed storage */
        "static double* __reo_array_dup_f64(const double* src, int64_t n) {\n"
        "    if (n < 0) n = 0;\n"
        "    double* a = (double*)malloc(sizeof(double) * (size_t)(n > 0 ? n : 1));\n"
        "    if (!a) { fprintf(stderr, \"runtime error: out of memory\\n\"); abort(); }\n"
        "    if (n > 0) memcpy(a, src, sizeof(double) * (size_t)n);\n"
        "    return a;\n"
        "}\n"
        "static double* __reo_array_repeat_f64(int64_t n, double val) {\n"
        "    if (n < 0) n = 0;\n"
        "    double* a = (double*)malloc(sizeof(double) * (size_t)(n > 0 ? n : 1));\n"
        "    if (!a) { fprintf(stderr, \"runtime error: out of memory\\n\"); abort(); }\n"
        "    for (int64_t i = 0; i < n; i++) a[i] = val;\n"
        "    return a;\n"
        "}\n"
        /* fat-pointer arrays (literals / repeat): {data, len} with bounds
 * checking on every element access. Replaces bare pointers that
         * silently read/write out of bounds */
        "typedef struct { int64_t* data; int64_t len; } __reo_arr_t;\n"
        "typedef struct { double* data; int64_t len; } __reo_arrf_t;\n"
        "static int64_t __reo_chk_idx(int64_t i, int64_t len, const char* what) {\n"
        "    if (i < 0 || i >= len) {\n"
        "        fprintf(stderr, \"runtime error: array index %lld out of bounds (len %lld) in %s\\n\",\n"
        "                (long long)i, (long long)len, what);\n"
        "        abort();\n"
        "    }\n"
        "    return i;\n"
        "}\n"
        "static __reo_arr_t __reo_arr_lit(const int64_t* src, int64_t n) {\n"
        "    __reo_arr_t a;\n"
        "    a.len = n < 0 ? 0 : n;\n"
        "    a.data = (int64_t*)malloc(sizeof(int64_t) * (size_t)(n > 0 ? n : 1));\n"
        "    if (!a.data) { fprintf(stderr, \"runtime error: out of memory\\n\"); abort(); }\n"
        "    if (n > 0) memcpy(a.data, src, sizeof(int64_t) * (size_t)n);\n"
        "    return a;\n"
        "}\n"
        "static __reo_arr_t __reo_arr_rep(int64_t n, int64_t val) {\n"
        "    __reo_arr_t a;\n"
        "    a.len = n < 0 ? 0 : n;\n"
        "    a.data = (int64_t*)malloc(sizeof(int64_t) * (size_t)(n > 0 ? n : 1));\n"
        "    if (!a.data) { fprintf(stderr, \"runtime error: out of memory\\n\"); abort(); }\n"
        "    for (int64_t i = 0; i < a.len; i++) a.data[i] = val;\n"
        "    return a;\n"
        "}\n"
        "static __reo_arrf_t __reo_arrf_lit(const double* src, int64_t n) {\n"
        "    __reo_arrf_t a;\n"
        "    a.len = n < 0 ? 0 : n;\n"
        "    a.data = (double*)malloc(sizeof(double) * (size_t)(n > 0 ? n : 1));\n"
        "    if (!a.data) { fprintf(stderr, \"runtime error: out of memory\\n\"); abort(); }\n"
        "    if (n > 0) memcpy(a.data, src, sizeof(double) * (size_t)n);\n"
        "    return a;\n"
        "}\n"
        "static __reo_arrf_t __reo_arrf_rep(int64_t n, double val) {\n"
        "    __reo_arrf_t a;\n"
        "    a.len = n < 0 ? 0 : n;\n"
        "    a.data = (double*)malloc(sizeof(double) * (size_t)(n > 0 ? n : 1));\n"
        "    if (!a.data) { fprintf(stderr, \"runtime error: out of memory\\n\"); abort(); }\n"
        "    for (int64_t i = 0; i < a.len; i++) a.data[i] = val;\n"
        "    return a;\n"
        "}\n"
        "static int64_t __reo_arr_get(__reo_arr_t* a, int64_t i) {\n"
        "    return a->data[__reo_chk_idx(i, a->len, \"array read\")];\n"
        "}\n"
        "static void __reo_arr_set(__reo_arr_t* a, int64_t i, int64_t v) {\n"
        "    a->data[__reo_chk_idx(i, a->len, \"array write\")] = v;\n"
        "}\n"
        "static double __reo_arrf_get(__reo_arrf_t* a, int64_t i) {\n"
        "    return a->data[__reo_chk_idx(i, a->len, \"array read\")];\n"
        "}\n"
        "static void __reo_arrf_set(__reo_arrf_t* a, int64_t i, double v) {\n"
        "    a->data[__reo_chk_idx(i, a->len, \"array write\")] = v;\n"
        "}\n"
        "static int64_t __reo_arr_len(const void* a, int64_t len) { (void)a; return len; }\n"
        /* svec helpers: string vector { char** data; len; cap }, elements are strdup'd strings */
        "typedef struct { char** data; int64_t len; int64_t cap; } __reo_svec_t;\n"
        "static __reo_svec_t* __reo_svec_new(void) {\n"
        "    __reo_svec_t* v = (__reo_svec_t*)malloc(sizeof(__reo_svec_t));\n"
        "    if (!v) { fprintf(stderr, \"runtime error: out of memory\\n\"); abort(); }\n"
        "    v->cap = 8; v->len = 0;\n"
        "    v->data = (char**)calloc((size_t)v->cap, sizeof(char*));\n"
        "    if (!v->data) { free(v); fprintf(stderr, \"runtime error: out of memory\\n\"); abort(); }\n"
        "    return v;\n"
        "}\n"
        "static void __reo_svec_push(__reo_svec_t* v, const char* s) {\n"
        "    if (v->len >= v->cap) {\n"
        "        v->cap *= 2;\n"
        "        v->data = (char**)realloc(v->data, sizeof(char*) * (size_t)v->cap);\n"
        "        if (!v->data) { fprintf(stderr, \"runtime error: out of memory\\n\"); abort(); }\n"
        "    }\n"
        "    const char* src = s ? s : \"\";\n"
        "    char* dup = (char*)malloc(strlen(src) + 1);\n"
        "    if (!dup) { fprintf(stderr, \"runtime error: out of memory\\n\"); abort(); }\n"
        "    strcpy(dup, src);\n"
        "    v->data[v->len++] = dup;\n"
        "}\n"
        "static const char* __reo_svec_get(__reo_svec_t* v, int64_t i) {\n"
        "    if (i < 0 || i >= v->len) return \"\";\n"
        "    return v->data[i];\n"
        "}\n"
        "static int64_t __reo_svec_len(__reo_svec_t* v) { return v->len; }\n"
        "static void __reo_svec_free(__reo_svec_t* v) {\n"
        "    if (!v) return;\n"
        "    for (int64_t i = 0; i < v->len; i++) free(v->data[i]);\n"
        "    free(v->data); free(v);\n"
        "}\n"
        /* dir helpers: directory traversal (POSIX dirent; mingw/ucrt64 ships a compat layer). Handle is i64 */
        "typedef struct { DIR* d; } __reo_dir_t;\n"
        "static int64_t __reo_dir_open(const char* path) {\n"
        "    if (!path) return -1;\n"
        "    DIR* d = opendir(path);\n"
        "    if (!d) return -1;\n"
        "    __reo_dir_t* h = (__reo_dir_t*)malloc(sizeof(__reo_dir_t));\n"
        "    if (!h) { closedir(d); return -1; }\n"
        "    h->d = d;\n"
        "    return (int64_t)(intptr_t)h;\n"
        "}\n"
        "static const char* __reo_dir_next(int64_t hh) {\n"
        "    __reo_dir_t* h = (__reo_dir_t*)(intptr_t)hh;\n"
        "    if (!h || !h->d) return \"\";\n"
        "    struct dirent* ent = readdir(h->d);\n"
        "    return ent ? ent->d_name : \"\";\n"
        "}\n"
        "static void __reo_dir_close(int64_t hh) {\n"
        "    __reo_dir_t* h = (__reo_dir_t*)(intptr_t)hh;\n"
        "    if (!h) return;\n"
        "    if (h->d) closedir(h->d);\n"
        "    free(h);\n"
        "}\n"
        /* path helpers */
        "static const char* __reo_path_join(const char* a, const char* b) {\n"
        "    const char* aa = a ? a : \"\"; const char* bb = b ? b : \"\";\n"
        "    size_t la = strlen(aa), lb = strlen(bb);\n"
        "    int need_sep = (la > 0 && aa[la-1] != '/') ? 1 : 0;\n"
        "    char* r = (char*)malloc(la + lb + 2);\n"
        "    if (!r) { fprintf(stderr, \"runtime error: out of memory\\n\"); abort(); }\n"
        "    memcpy(r, aa, la);\n"
        "    if (need_sep) r[la++] = '/';\n"
        "    memcpy(r + la, bb, lb);\n"
        "    r[la + lb] = 0;\n"
        "    return r;\n"
        "}\n"
        "static const char* __reo_path_ext(const char* p) {\n"
        "    if (!p) return \"\";\n"
        "    const char* dot = strrchr(p, '.');\n"
        "    const char* sep = strrchr(p, '/');\n"
        "    if (!dot || (sep && dot < sep)) return \"\";\n"
        "    char* r = (char*)malloc(strlen(dot) + 1);\n"
        "    if (!r) { fprintf(stderr, \"runtime error: out of memory\\n\"); abort(); }\n"
        "    strcpy(r, dot); return r;\n"
        "}\n"
        "static const char* __reo_path_base(const char* p) {\n"
        "    if (!p) return \"\";\n"
        "    const char* sep = strrchr(p, '/');\n"
        "    const char* base = sep ? sep + 1 : p;\n"
        "    char* r = (char*)malloc(strlen(base) + 1);\n"
        "    if (!r) { fprintf(stderr, \"runtime error: out of memory\\n\"); abort(); }\n"
        "    strcpy(r, base); return r;\n"
        "}\n"
        "static bool __reo_path_isdir(const char* p) {\n"
        "    if (!p) return false;\n"
        "    struct stat st;\n"
        "    if (stat(p, &st) != 0) return false;\n"
        "    return S_ISDIR(st.st_mode);\n"
        "}\n"
        /* proc helper: subprocess (wraps system) */
        "static int64_t __reo_proc_run(const char* cmd) {\n"
        "    if (!cmd) return -1;\n"
        "    return (int64_t)system(cmd);\n"
        "}\n"
        /* system helpers */
        "static int64_t __reo_argv_len = 0;\n"
        "static const char** __reo_argv_list = NULL;\n"
        "static void __reo_init_argv(int argc, char** argv) {\n"
        "    __reo_argv_len = argc; __reo_argv_list = (const char**)argv;\n"
        "}\n"
        "static int64_t __reo_argv_len_fn(void) { return __reo_argv_len; }\n"
        "static const char* __reo_argv_get_fn(int64_t i) {\n"
        "    if (i < 0 || i >= __reo_argv_len) return \"\";\n"
        "    return __reo_argv_list[i];\n"
        "}\n"
        "static const char* __reo_stdin_read(void) {\n"
        "    size_t cap = 256, len = 0;\n"
        "    char* buf = (char*)malloc(cap);\n"
        "    if (!buf) return \"\";\n"
        "    int c;\n"
        "    while ((c = getchar()) != EOF && c != '\\n') {\n"
        "        if (len + 1 >= cap) { cap *= 2; buf = (char*)realloc(buf, cap); }\n"
        "        buf[len++] = (char)c;\n"
        "    }\n"
        "    buf[len] = 0; return buf;\n"
        "}\n\n");
    re0_buffer_write_str(out,
    /* GC runtime (mark-sweep with mode selection) */
        /* mode: 0=none(no-op), 1=auto(threshold collect), 2=manual(API only) */
        "typedef struct __reo_gc_node {\n"
        "    void *ptr; size_t size; int ref_count; int kind;\n"
        "    struct __reo_gc_node *next; bool marked;\n"
        "    void (*dtor)(void *);\n"
        "} __reo_gc_node_t;\n"
        "static struct {\n"
        "    __reo_gc_node_t *head; __reo_gc_node_t **roots;\n"
        "    int root_count, root_cap, total_count, threshold, mode;\n"
        "} __reo_gc = { NULL, NULL, 0, 0, 0, 1024, 0 };\n"
        "static void __reo_gc_mark(__reo_gc_node_t *n) {\n"
        "    if (!n || n->marked) return; n->marked = true;\n"
        "}\n"
        "static void __reo_gc_sweep(void) {\n"
        "    __reo_gc_node_t **pp = &__reo_gc.head;\n"
        "    while (*pp) {\n"
        "        __reo_gc_node_t *n = *pp;\n"
        "        if (!n->marked && n->ref_count <= 0 && n->kind != 3) {\n"
        "            *pp = n->next;\n"
        "            if (n->dtor) n->dtor(n->ptr);\n"
        "            free(n->ptr); free(n);\n"
        "            __reo_gc.total_count--;\n"
        "        } else { n->marked = false; pp = &n->next; }\n"
        "    }\n"
        "}\n"
        "static void __reo_gc_collect(void) {\n"
        "    if (__reo_gc.mode == 0) return;\n"
        "    for (int i = 0; i < __reo_gc.root_count; i++)\n"
        "        __reo_gc_mark(__reo_gc.roots[i]);\n"
        "    __reo_gc_sweep();\n"
        "}\n"
        "static int64_t __reo_gc_stats(void) {\n"
        "    return (int64_t)__reo_gc.total_count;\n"
        "}\n"
        "static void __reo_gc_add_root(void *p) {\n"
        "    if (!p) return;\n"
        "    if (__reo_gc.root_count >= __reo_gc.root_cap) {\n"
        "        int nc = __reo_gc.root_cap ? __reo_gc.root_cap * 2 : 16;\n"
        "        __reo_gc_node_t **nr = (__reo_gc_node_t**)realloc(\n"
        "            __reo_gc.roots, sizeof(__reo_gc_node_t*) * (size_t)nc);\n"
        "        if (!nr) { fprintf(stderr, \"runtime error: out of memory\\n\"); abort(); }\n"
        "        __reo_gc.roots = nr; __reo_gc.root_cap = nc;\n"
        "    }\n"
        "    __reo_gc.roots[__reo_gc.root_count++] = (__reo_gc_node_t*)p;\n"
        "}\n"
        "static void __reo_gc_remove_root(void *p) {\n"
        "    if (!p) return;\n"
        "    for (int i = 0; i < __reo_gc.root_count; i++)\n"
        "        if (__reo_gc.roots[i] == (__reo_gc_node_t*)p) {\n"
        "            __reo_gc.roots[i] = __reo_gc.roots[--__reo_gc.root_count];\n"
        "            return;\n"
        "        }\n"
        "}\n"
        "static void *__reo_gc_alloc(size_t sz) {\n"
        "    if (sz == 0) return NULL;\n"
        "    __reo_gc_node_t *n = (__reo_gc_node_t*)malloc(sizeof(__reo_gc_node_t));\n"
        "    if (!n) { fprintf(stderr, \"runtime error: out of memory\\n\"); abort(); }\n"
        "    n->ptr = malloc(sz);\n"
        "    if (!n->ptr) { free(n); fprintf(stderr, \"runtime error: out of memory\\n\"); abort(); }\n"
        "    n->size = sz; n->ref_count = 1; n->kind = 2;\n"
        "    n->next = __reo_gc.head; __reo_gc.head = n;\n"
        "    __reo_gc.total_count++;\n"
        "    if (__reo_gc.mode == 1 && __reo_gc.total_count > __reo_gc.threshold)\n"
        "        __reo_gc_collect();\n"
        "    return n->ptr;\n"
        "}\n\n");
    re0_buffer_write_str(out,
    /* spawn/await concurrency runtime (pthread phase 0) */
        "#include <pthread.h>\n\n"
        "typedef int64_t (*__reo_task_fn)(void);\n"
        "typedef struct { __reo_task_fn fn; size_t result_len; char result_buf[128]; } __reo_task_ctx;\n"
        "typedef struct { pthread_t thread; __reo_task_ctx* ctx; int state; } __reo_task_slot;\n"
        "static __reo_task_slot __reo_tasks[256];\n"
        "static pthread_mutex_t __reo_task_mtx = PTHREAD_MUTEX_INITIALIZER;\n\n"
        "static void* __reo_task_trampoline(void* arg) {\n"
        "    __reo_task_ctx* c = (__reo_task_ctx*)arg;\n"
        "    int64_t ret = c->fn();\n"
        "    memcpy(c->result_buf, &ret, sizeof(int64_t));\n"
        "    c->result_len = sizeof(int64_t);\n"
        "    return NULL;\n"
        "}\n\n"
        "uint64_t __reo_rt_spawn(__reo_task_fn fn) {\n"
        "    if (!fn) return 0;\n"
        "    __reo_task_ctx* ctx = calloc(1, sizeof(__reo_task_ctx));\n"
        "    if (!ctx) return 0;\n"
        "    ctx->fn = fn;\n"
        "    pthread_mutex_lock(&__reo_task_mtx);\n"
        "    int slot = -1;\n"
        "    for (int i = 0; i < 256; i++) if (__reo_tasks[i].state == 0) { slot = i; break; }\n"
        "    if (slot < 0) { pthread_mutex_unlock(&__reo_task_mtx); free(ctx); return 0; }\n"
        "    __reo_tasks[slot].ctx = ctx;\n"
        "    __reo_tasks[slot].state = 1;\n"
        "    int create_rc = pthread_create(&__reo_tasks[slot].thread, NULL, __reo_task_trampoline, ctx);\n"
        "    if (create_rc != 0) { __reo_tasks[slot].ctx = NULL; __reo_tasks[slot].state = 0; pthread_mutex_unlock(&__reo_task_mtx); free(ctx); return 0; }\n"
        "    pthread_mutex_unlock(&__reo_task_mtx);\n"
        "    return (uint64_t)(slot + 1);\n"
        "}\n\n"
        "int32_t __reo_rt_await(uint64_t task_id, void* out, size_t out_cap) {\n"
        "    if (task_id == 0 || task_id > 256) return -1;\n"
        "    int slot = (int)task_id - 1;\n"
        "    pthread_mutex_lock(&__reo_task_mtx);\n"
        "    if (__reo_tasks[slot].state != 1) { pthread_mutex_unlock(&__reo_task_mtx); return -1; }\n"
        "    __reo_tasks[slot].state = 2;\n"
        "    pthread_t thread = __reo_tasks[slot].thread;\n"
        "    __reo_task_ctx* c = __reo_tasks[slot].ctx;\n"
        "    pthread_mutex_unlock(&__reo_task_mtx);\n"
        "    if (pthread_join(thread, NULL) != 0) return -2;\n"
        "    size_t copy = c->result_len < out_cap ? c->result_len : out_cap;\n"
        "    if (out && copy > 0) memcpy(out, c->result_buf, copy);\n"
        "    int32_t ret = (c->result_len > 0) ? 0 : -2;\n"
        "    free(c);\n"
        "    pthread_mutex_lock(&__reo_task_mtx);\n"
        "    __reo_tasks[slot].ctx = NULL;\n"
        "    __reo_tasks[slot].state = 0;\n"
        "    pthread_mutex_unlock(&__reo_task_mtx);\n"
        "    return ret;\n"
        "}\n\n");
}
